//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleToCategory
    {
        public System.Guid ArticleToCategoryId { get; set; }
        public System.DateTime ArticleToCategoryCreateDateTime { get; set; }
        public int ArticleToCategoryIsRemoved { get; set; }
        public System.Guid ArticleToCategoryCategoryId { get; set; }
        public System.Guid ArticleToCategoryArticleId { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Category Category { get; set; }
    }
}
