//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public System.Guid CommentId { get; set; }
        public System.DateTime CommentCreateDateTime { get; set; }
        public int CommentIsRemoved { get; set; }
        public string CommentContent { get; set; }
        public System.Guid CommentUserId { get; set; }
        public System.Guid CommentArticleId { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual User User { get; set; }
    }
}
