//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAndFollowing
    {
        public System.Guid UserAndFollowingId { get; set; }
        public Nullable<System.DateTime> UserAndFollowingCreateDateTime { get; set; }
        public int UserAndFollowingIsRemoved { get; set; }
        public System.Guid UserAndFollowingUserId { get; set; }
        public System.Guid UserAndFollowingFollowingId { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
